import account access key checker
mynearwallet/my-near-wallet pull request #222
Opened 2024-03-11 10:29 UTC by superokid

## Issues
Deleted full access key account was able imported into wallet, & user cant do any transaction

## Changes description
when import deleted account / deleted full access key will show error

## Preview
<img width="805" alt="Screen Shot 2024-03-11 at 17 22 12" src="https://github.com/mynearwallet/my-near-wallet/assets/22742847/b24b03a7-0f17-4d40-9c75-dee6d2331e2f">

2024-03-13 01:16 UTC, SteveKok commented on packages/frontend/src/utils/wallet.ts
deletedAccount might be overwritten in the for loop.

If this is an intended behavior, maybe put a comment to explain why we no need to worry that it get overwritten.

2024-03-13 01:20 UTC, SteveKok commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
when user input a seed phrase / private key that doesn't corresponding to any account.

My Near Wallet will create a zero balance implicit account and ask user to fund it.

This code edit solved the problem of importing deleted implicit account, but totally change the behaviour of my near wallet.

2024-03-13 01:24 UTC, SteveKok commented on packages/frontend/src/utils/wallet.ts
If deletedAccount is only a flag that keep track of whether the public key have any deleted account, maybe use 

```
let deletedAccount = false;

for (const accountId of accountsSet) {
    if (!(await this.accountExists(accountId))) {
        accountsSet.delete(accountId);
        deletedAccount = true;
    }
}
```

This will let programmer who read this code knows that we don't need to worry about deletedAccount being overwritten

2024-03-13 01:33 UTC, SteveKok commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
Test procedure:

Open MNW in incognito
Create an account
Copy the seed phrase
Without funding the account, close the browser
Open MNW in incognito again
Import account using the copied seed phrase
In current MNW environment, you can successfully import the account.

But after this PR, the behaviour might be changed.

2024-03-13 02:08 UTC, superokid commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
I tested with that step, it still can import the account zerobalance1.testnet

2024-03-13 02:13 UTC, superokid commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
that code is to create account when fail import, but from user perspective would it be easier for user if they do import account just as import?
or maybe there is another usecase that code exist before?

I work on new feature manual import account, which import any seedphrase that match with accountId & it check for valid access key, will this feature solve that part if delivered together?

2024-03-13 02:23 UTC, SteveKok commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
test the same procedure as mentioned in mainnet

2024-03-13 09:55 UTC, superokid commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
have put back the code

2024-03-14 02:56 UTC, SteveKok requested changes

2024-03-14 02:56 UTC, SteveKok commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
After this change, now, importing deleted access key implicit account will success...

Which, broken the test or description of this PR.

2024-03-14 05:48 UTC, superokid commented on packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
fixed added 1 more case for unmatch keypair

2024-03-14 07:08 UTC, SteveKok requested changes
Now you make a valid access key to become unable to import.

<img width="1606" alt="Screenshot 2024-03-14 at 3 04 59 PM" src="https://github.com/mynearwallet/my-near-wallet/assets/125173477/0f4cab4a-7f42-4162-b303-72946a186171">

Screenshot above showing an access key that can sign transaction.

<img width="1624" alt="Screenshot 2024-03-14 at 3 05 36 PM" src="https://github.com/mynearwallet/my-near-wallet/assets/125173477/b7db3113-6761-4f6e-b1fd-f5a6f2fd6780">

This screenshot is coming from this PR, which the valid access key can't be import

2024-03-14 09:11 UTC, SteveKok requested changes
After this commit...

I can import using a deleted access key, the account have balance, but it will pop up telling me unfunded. See screenshot: 

<img width="1641" alt="Screenshot 2024-03-14 at 5 09 04 PM" src="https://github.com/mynearwallet/my-near-wallet/assets/125173477/9678799f-f135-4cea-b321-257dcab9e32e">

And, I can't sign any transaction.

<img width="1671" alt="Screenshot 2024-03-14 at 5 09 24 PM" src="https://github.com/mynearwallet/my-near-wallet/assets/125173477/ea7e4134-135f-4804-8670-904b64fd87a8">

2024-03-15 10:27 UTC, SteveKok approved these changes

2024-03-15 10:29 UTC, SteveKok commented
The following case had been tested inside mainnet environment:

- Seed phrase that haven't been used before will be imported as "zero balance implicit account"
- Seed phrase that currently belongs to a valid account will be imported as "normal account"
- Seed phrase that being deleted won't be imported

2024-03-15 16:01 UTC, merged