fix(token): some token not showing, update blackdragon icon
mynearwallet/my-near-wallet pull request #227
Opened 2024-03-26 05:58 UTC by superokid

## Issues
fix Blackdragon, $Meta token not showing hidden by blacklisted token feature
update blackdragon icon
<img width="769" alt="Screen Shot 2024-03-26 at 12 48 17" src="https://github.com/mynearwallet/my-near-wallet/assets/22742847/e7294c7b-03f1-46d2-9742-ddf3bb9c663a">

2024-03-26 08:51 UTC, SteveKok requested changes
This PR is dangerous. It might unflag some tokens that originally flagged by us as malicious.

It is safer to whitelist tokens that we feel not a scam, instead of changing the rules.

2024-03-26 08:51 UTC, SteveKok commented on packages/e2e-tests/recover/manualImport.spec.ts
Please uncommit this and open a new PR.

Don't push commits that unrelated to the current PR title.

2024-03-26 08:51 UTC, SteveKok commented on packages/frontend/src/redux/slices/tokens/index.js
dollar sign `$` was filtered to make sure tokens such as `$META` won't be displayed.

Symbol length was set to `10` to make sure tokens name can't be meaningful enough for english meaning.

Please whitelist the blackdragon token by changing the following code:
```typescript
if (
    ['Native USDT', 'Native USDC', 'Bridged USDC', 'Bridged USDT'].includes(
        onChainFTMetadata.symbol
    )
) {
    return true;
}
```

2024-03-26 09:24 UTC, superokid commented on packages/e2e-tests/recover/manualImport.spec.ts
fixing test every commit is better than hold into another branch

2024-03-26 09:25 UTC, superokid commented on packages/frontend/src/redux/slices/tokens/index.js
can show example of scam token that can pass the check?
how many token there will be hidden, & will need us to keep whitelist

2024-03-27 07:21 UTC, SteveKok approved these changes

2024-03-27 07:47 UTC, merged